**24ADI006 - DEEP LEARNING**

**Name:Priya Dharshini R\
ROll NO.:24BAD092**

**Task1: Create a single layer perceptron class. Implement the AND, OR binary logic using the perceptron. improve the model accuracy.**

**Step 1:** Import the Required Library

**Step 2:** Create the Single Layer Perceptron Class

**Step 3:** Print Student Details

**Step 4**: Create the Input Dataset (Truth Table)

**Step 5:** Train the Perceptron for the AND Gate

**Step 6:** Display the AND Gate Predictions, Final Weights, and Accuracy

**Step 7:** Train the Perceptron for the OR Gate

**Step 8:** Display the OR Gate Predictions, Final Weights, and Accuracy


In [18]:
import numpy as np

# Single Layer Perceptron Class
class Perceptron:
    def __init__(self, num_inputs, learning_rate=0.1):
        # Initialize weights (including bias)
        self.weights = np.random.rand(num_inputs + 1)
        self.learning_rate = learning_rate

    # Linear function
    def linear(self, inputs):
        return np.dot(inputs, self.weights[1:]) + self.weights[0]

    # Activation Function (Heaviside Step Function)
    def Heaviside_step_fn(self, z):
        if z >= 0:
            return 1
        else:
            return 0

    # Prediction
    def predict(self, inputs):
        z = self.linear(inputs)
        return self.Heaviside_step_fn(z)

    # Loss (Error)
    def loss(self, prediction, target):
        return target - prediction

    # Training
    def train(self, inputs, target):
        prediction = self.predict(inputs)
        error = self.loss(prediction, target)

        # Update weights
        self.weights[1:] += self.learning_rate * error * inputs

        # Update bias
        self.weights[0] += self.learning_rate * error

    # Fit Model
    def fit(self, X, y, epochs):
        for epoch in range(epochs):
            for inputs, target in zip(X, y):
                self.train(inputs, target)

    # Accuracy
    def accuracy(self, X, y):
        correct = 0
        for inputs, target in zip(X, y):
            if self.predict(inputs) == target:
                correct += 1
        return (correct / len(y)) * 100


# Student Details
print("Name     : Priya Dharshini R")
print("Roll No. : 24BAD092")
print("=" * 50)

# Dataset (Truth Table)
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# AND Gate
print("\nTraining Perceptron for AND Gate")

y_and = np.array([0, 0, 0, 1])

model_and = Perceptron(num_inputs=2, learning_rate=0.1)
model_and.fit(X, y_and, epochs=100)

print("\nFinal Weights (AND Gate):")
print(model_and.weights)

print("\nPredictions (AND Gate):")
for x in X:
    print(f"{x} -> {model_and.predict(x)}")

print("\nAccuracy (AND Gate): {:.2f}%".format(model_and.accuracy(X, y_and)))

# OR Gate
print("\n" + "=" * 50)
print("Training Perceptron for OR Gate")

y_or = np.array([0, 1, 1, 1])

model_or = Perceptron(num_inputs=2, learning_rate=0.1)
model_or.fit(X, y_or, epochs=100)

print("\nFinal Weights (OR Gate):")
print(model_or.weights)

print("\nPredictions (OR Gate):")
for x in X:
    print(f"{x} -> {model_or.predict(x)}")

print("\nAccuracy (OR Gate): {:.2f}%".format(model_or.accuracy(X, y_or)))

Name     : Priya Dharshini R
Roll No. : 24BAD092

Training Perceptron for AND Gate

Final Weights (AND Gate):
[-0.49142931  0.30756647  0.24929223]

Predictions (AND Gate):
[0 0] -> 0
[0 1] -> 0
[1 0] -> 0
[1 1] -> 1

Accuracy (AND Gate): 100.00%

Training Perceptron for OR Gate

Final Weights (OR Gate):
[-0.08961708  0.75555114  0.22879817]

Predictions (OR Gate):
[0 0] -> 0
[0 1] -> 1
[1 0] -> 1
[1 1] -> 1

Accuracy (OR Gate): 100.00%


**Task2: Use a random dataset to train, predict and calculate the accuracy of the model.**



**Step 1:** Import the Required Libraries

**Step 2:** Print Student Details

**Step 3:** Create the Single Layer Perceptron Class

**Step 4:** Generate the Random Dataset

**Step 5:** Display the Generated Dataset

**Step 6:** Create the Perceptron Model

**Step 7:** Train the Perceptron Model

**Step 8:** Predict the Output for the First 10 Samples

**Step 9:** Calculate and Display the Model Accuracy

**Step 10:** Display the Final Weights


In [19]:
import numpy as np
import pandas as pd

# Student Details
print("Name     : Priya Dharshini R")
print("Roll No. : 24BAD092")
print("=" * 50)


# Single Layer Perceptron Class

class Perceptron:

    def __init__(self, num_inputs, learning_rate=0.1):
        self.weights = np.random.rand(num_inputs + 1)
        self.learning_rate = learning_rate

    # Linear Function
    def linear(self, inputs):
        return np.dot(inputs, self.weights[1:]) + self.weights[0]

    # Activation Function
    def activation(self, z):
        if z >= 0:
            return 1
        else:
            return 0

    # Prediction
    def predict(self, inputs):
        z = self.linear(inputs)
        return self.activation(z)

    # Training
    def train(self, inputs, target):
        prediction = self.predict(inputs)
        error = target - prediction

        # Update weights
        self.weights[1:] += self.learning_rate * error * inputs

        # Update bias
        self.weights[0] += self.learning_rate * error

    # Fit Model
    def fit(self, X, y, epochs):
        for epoch in range(epochs):
            for inputs, target in zip(X, y):
                self.train(inputs, target)

    # Accuracy
    def accuracy(self, X, y):
        predictions = [self.predict(x) for x in X]
        return np.mean(np.array(predictions) == y) * 100

# Generate Random Dataset

np.random.seed(42)

# Generate 100 random samples with 2 binary features
X = np.random.randint(0, 2, (100, 2))

# Generate target using OR logic
y = np.where((X[:,0] == 1) | (X[:,1] == 1), 1, 0)

# Display Dataset
dataset = pd.DataFrame(X, columns=["Feature1", "Feature2"])
dataset["Target"] = y

print("\nRandom Dataset (First 10 Rows)")
print(dataset.head(10))

# Create Model

model = Perceptron(num_inputs=2, learning_rate=0.1)

# Train Model

print("\nTraining the Perceptron...")
model.fit(X, y, epochs=100)
print("Training Completed!")

# Predictions

print("\nPredictions (First 10 Samples)")
print("-" * 45)

for i in range(10):
    prediction = model.predict(X[i])
    print(f"Input: {X[i]}  Actual: {y[i]}  Predicted: {prediction}")

# Accuracy

accuracy = model.accuracy(X, y)

print("\nModel Accuracy: {:.2f}%".format(accuracy))

# Final Weights

print("\nFinal Weights:")
print(model.weights)

Name     : Priya Dharshini R
Roll No. : 24BAD092

Random Dataset (First 10 Rows)
   Feature1  Feature2  Target
0         0         1       1
1         0         0       0
2         0         1       1
3         0         0       0
4         0         1       1
5         0         0       0
6         0         0       0
7         1         0       1
8         1         1       1
9         1         0       1

Training the Perceptron...
Training Completed!

Predictions (First 10 Samples)
---------------------------------------------
Input: [0 1]  Actual: 1  Predicted: 1
Input: [0 0]  Actual: 0  Predicted: 0
Input: [0 1]  Actual: 1  Predicted: 1
Input: [0 0]  Actual: 0  Predicted: 0
Input: [0 1]  Actual: 1  Predicted: 1
Input: [0 0]  Actual: 0  Predicted: 0
Input: [0 0]  Actual: 0  Predicted: 0
Input: [1 0]  Actual: 1  Predicted: 1
Input: [1 1]  Actual: 1  Predicted: 1
Input: [1 0]  Actual: 1  Predicted: 1

Model Accuracy: 100.00%

Final Weights:
[-0.06857081  0.63641041  0.31435598]
